### ISSUE TITLE
react-input-checkbox dosent works on create react app

### ISSUE THREAD

**Issue by lironmo** [justredpaul/react-input-checkbox#10]
see
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-input-checkbox@0.1.6
npm ERR! node_modules/react-input-checkbox
npm ERR!   react-input-checkbox@"*" from the root project

**Comment by koenidv** [comment]
Same - found **react@18.1.0**, could not resolve dependency **react@"^16.0.0"**

**Comment by justredpaul** [comment]
I apologize for the significant delay in responding to this issue.

I've updated package to **@1.1.0** version with support of **react@18.1.0** and tested with a generated blank create-react-app application.

Hope that will fix the error.
